export const collegeList = [
  { label: "Hindu College, Delhi", value: "Hindu College, Delhi" },
  { label: "Miranda House, Delhi", value: "Miranda House, Delhi" },
  { label: "Rama Krishna Mission Vivekananda Centenary College, Kolkata", value: "Rama Krishna Mission Vivekananda Centenary College, Kolkata" },
  { label: "St. Stephens's College, Delhi", value: "St. Stephens's College, Delhi" },
  { label: "Atma Ram Sanatan Dharm College, New Delhi", value: "Atma Ram Sanatan Dharm College, New Delhi" },
  { label: "St. Xavier's College, Kolkata", value: "St. Xavier's College, Kolkata" },
  { label: "PSGR Krishnammal College for Women, Coimbatore", value: "PSGR Krishnammal College for Women, Coimbatore" },
  { label: "Loyola College, Chennai", value: "Loyola College, Chennai" },
  { label: "Kirori Mal College, Delhi", value: "Kirori Mal College, Delhi" },
  { label: "Lady Shri Ram College for Women, New Delhi", value: "Lady Shri Ram College for Women, New Delhi" },
  { label: "PSG College of Arts and Science, Coimbatore", value: "PSG College of Arts and Science, Coimbatore" },
  { label: "Hans Raj College, Delhi", value: "Hans Raj College, Delhi" },
  { label: "Presidency College, Chennai", value: "Presidency College, Chennai" },
  { label: "Madras Christian College, Chennai", value: "Madras Christian College, Chennai" },
  { label: "Thiagarajar College, Madurai", value: "Thiagarajar College, Madurai" },
  { label: "Deshbandhu College, New Delhi", value: "Deshbandhu College, New Delhi" },
  { label: "Ramakrishna Mission Vidyamandira, Howrah", value: "Ramakrishna Mission Vidyamandira, Howrah" },
  { label: "Acharya Narendra Dev College, New Delhi", value: "Acharya Narendra Dev College, New Delhi" },
  { label: "Shri Ram College of Commerce, Delhi", value: "Shri Ram College of Commerce, Delhi" },
  { label: "Rajagiri College of Social Sciences, Ernakulam", value: "Rajagiri College of Social Sciences, Ernakulam" },
  { label: "Sri Venkateswara College, Delhi", value: "Sri Venkateswara College, Delhi" },
  { label: "University College, Thiruvananthapuram", value: "University College, Thiruvananthapuram" },
  { label: "Lady Irwin College, Delhi", value: "Lady Irwin College, Delhi" },
  { label: "Ramakrishna Mission Residential College, Kolkata", value: "Ramakrishna Mission Residential College, Kolkata" },
  { label: "St. Joseph's College, Tiruchirappalli", value: "St. Joseph's College, Tiruchirappalli" },
  { label: "Deen Dayal Upadhyaya College, New Delhi", value: "Deen Dayal Upadhyaya College, New Delhi" },
  { label: "Bhaskaracharya College of Applied Sciences, New Delhi", value: "Bhaskaracharya College of Applied Sciences, New Delhi" },
  { label: "V.O. Chidambaram College, Thoothukudi", value: "V.O. Chidambaram College, Thoothukudi" },
  { label: "Maitreyi College, New Delhi", value: "Maitreyi College, New Delhi" },
  { label: "Stella Maris College for Women, Chennai", value: "Stella Maris College for Women, Chennai" },
  { label: "Gargi College, Delhi", value: "Gargi College, Delhi" },
  { label: "Midnapore College, Midnapore", value: "Midnapore College, Midnapore" },
  { label: "Bishop Heber College, Tiruchirappalli", value: "Bishop Heber College, Tiruchirappalli" },
  { label: "Dyal Singh College, New Delhi", value: "Dyal Singh College, New Delhi" },
  { label: "Pachhunga University College, Aizawl", value: "Pachhunga University College, Aizawl" },
  { label: "St. Xavier's College, Palayamkottai", value: "St. Xavier's College, Palayamkottai" },
  { label: "Sri Krishna Arts and Science College, Coimbatore", value: "Sri Krishna Arts and Science College, Coimbatore" },
  { label: "Shaheed Rajguru College of Applied Sciences for Women, Delhi", value: "Shaheed Rajguru College of Applied Sciences for Women, Delhi" },
  { label: "Sri Guru Gobind Singh College of Commerce, Delhi", value: "Sri Guru Gobind Singh College of Commerce, Delhi" },
  { label: "Jesus & Mary College, New Delhi", value: "Jesus & Mary College, New Delhi" },
  { label: "Holy Cross College, Tiruchirappalli", value: "Holy Cross College, Tiruchirappalli" },
  { label: "Nesamony Memorial Christian College, Marthandam", value: "Nesamony Memorial Christian College, Marthandam" },
  { label: "Kamala Nehru College, Delhi", value: "Kamala Nehru College, Delhi" },
  { label: "Dhanalakshmi Srinivasan College of Arts and Science for Women, Perambalur", value: "Dhanalakshmi Srinivasan College of Arts and Science for Women, Perambalur" },
  { label: "Fergusson College (Autonomous), Pune", value: "Fergusson College (Autonomous), Pune" },
  { label: "St. Teresa's College, Ernakulam", value: "St. Teresa's College, Ernakulam" },
  { label: "Sacred Heart College (Autonomous), Tirupattur", value: "Sacred Heart College (Autonomous), Tirupattur" },
  { label: "Sacred Heart College, Kochi", value: "Sacred Heart College, Kochi" },
  { label: "Govt. College for Women, Thiruvananthapuram", value: "Govt. College for Women, Thiruvananthapuram" },
  { label: "Shivaji College, Delhi", value: "Shivaji College, Delhi" },
  { label: "Govt Home Science College, Chandigarh", value: "Govt Home Science College, Chandigarh" },
  { label: "Kongunadu Arts and Science College, Coimbatore", value: "Kongunadu Arts and Science College, Coimbatore" },
  { label: "Maharaja's College, Ernakulam", value: "Maharaja's College, Ernakulam" },
  { label: "The American College, Madurai", value: "The American College, Madurai" },
  { label: "St. Joseph's College of Commerce, Bengaluru", value: "St. Joseph's College of Commerce, Bengaluru" },
  { label: "Sri Ramakrishna College of Arts and Science, Coimbatore", value: "Sri Ramakrishna College of Arts and Science, Coimbatore" },
  { label: "St. Thomas College, Thrissur", value: "St. Thomas College, Thrissur" },
  { label: "St. Aloysius College, Mangaluru", value: "St. Aloysius College, Mangaluru" },
  { label: "Jamal Mohamed College, Tiruchirappalli", value: "Jamal Mohamed College, Tiruchirappalli" },
  { label: "Kristu Jayanti College, Bengaluru", value: "Kristu Jayanti College, Bengaluru" },
  { label: "St. Joseph's College, Devagiri", value: "St. Joseph's College, Devagiri" },
  { label: "Bishop Moore College, Alappuzha", value: "Bishop Moore College, Alappuzha" },
  { label: "Ayya Nadar Janaki Ammal College, Sivakasi", value: "Ayya Nadar Janaki Ammal College, Sivakasi" },
  { label: "Government Institute of Science, Nagpur", value: "Government Institute of Science, Nagpur" },
  { label: "Ramanujan College, New Delhi", value: "Ramanujan College, New Delhi" },
  { label: "Mar Ivanios College, Thiruvananthapuram", value: "Mar Ivanios College, Thiruvananthapuram" },
  { label: "Government Arts College, Coimbatore", value: "Government Arts College, Coimbatore" },
  { label: "Women's Christian College, Chennai", value: "Women's Christian College, Chennai" },
  { label: "Ahmednagar Jilha Maratha Vidya Prasarak Samaj's New Arts Commerce & Science College, Ahmednagar", value: "Ahmednagar Jilha Maratha Vidya Prasarak Samaj's New Arts Commerce & Science College, Ahmednagar" },
  { label: "Anna Adarsh College for Women, Chennai", value: "Anna Adarsh College for Women, Chennai" },
  { label: "Aryabhatta College, Delhi", value: "Aryabhatta College, Delhi" },
  { label: "Baselius College, Kottayam", value: "Baselius College, Kottayam" },
  { label: "Bharathi Women's College, Chennai", value: "Bharathi Women's College, Chennai" },
  { label: "Bhavans Vivekananda College of Science, Humanities and Commerce, Secunderabad", value: "Bhavans Vivekananda College of Science, Humanities and Commerce, Secunderabad" },
  { label: "Bon Secours College for Women, Thanjavur", value: "Bon Secours College for Women, Thanjavur" },
  { label: "C. Abdul Hakeem College, Melvisharam", value: "C. Abdul Hakeem College, Melvisharam" },
  { label: "Catholicate College, Pathanamthitta", value: "Catholicate College, Pathanamthitta" },
  { label: "Cauvery College for Women, Tiruchirappalli", value: "Cauvery College for Women, Tiruchirappalli" },
  { label: "Dempo Charities Trust Dhempe College of Arts & Science, Panaji", value: "Dempo Charities Trust Dhempe College of Arts & Science, Panaji" },
  { label: "Government College for Women, Kumbakonam", value: "Government College for Women, Kumbakonam" },
  { label: "Government College for Women, Parade Ground, Jammu", value: "Government College for Women, Parade Ground, Jammu" },
  { label: "Govt. College, Nedumangad", value: "Govt. College, Nedumangad" },
  { label: "Indira Gandhi College of Arts and Science, Puducherry", value: "Indira Gandhi College of Arts and Science, Puducherry" },
  { label: "Justice Basher Ahmed Sayeed College for Women, Chennai", value: "Justice Basher Ahmed Sayeed College for Women, Chennai" },
  { label: "Kalindi College, Delhi", value: "Kalindi College, Delhi" },
  { label: "Kumaraguru College of Liberal Arts and Science, Coimbatore", value: "Kumaraguru College of Liberal Arts and Science, Coimbatore" },
  { label: "Kunthavai Naacchiyaar Government Arts College for Women, Thanjavur", value: "Kunthavai Naacchiyaar Government Arts College for Women, Thanjavur" },
  { label: "Loreto College, Kolkata", value: "Loreto College, Kolkata" },
  { label: "Maharaja Surajmal Institute, Delhi", value: "Maharaja Surajmal Institute, Delhi" },
  { label: "Marian College, Kuttikanam", value: "Marian College, Kuttikanam" },
  { label: "Mata Sundri College for Women, New Delhi", value: "Mata Sundri College for Women, New Delhi" },
  { label: "Mercy College, Palakkad", value: "Mercy College, Palakkad" },
  { label: "MG College, Thiruvananthapuram", value: "MG College, Thiruvananthapuram" },
  { label: "MOP Vaishnav College for Women, Chennai", value: "MOP Vaishnav College for Women, Chennai" },
  { label: "Mount Carmel College (Autonomous), Bengaluru", value: "Mount Carmel College (Autonomous), Bengaluru" },
  { label: "Nehru Arts & Science College, Kasaragod", value: "Nehru Arts & Science College, Kasaragod" },
  { label: "Nirmala College for Women, Coimbatore", value: "Nirmala College for Women, Coimbatore" },
  { label: "Nirmala College, Muvattupuzha", value: "Nirmala College, Muvattupuzha" },
  { label: "Nirmalagiri College, Kannur", value: "Nirmalagiri College, Kannur" },
  { label: "Payyannur College, Payyannur", value: "Payyannur College, Payyannur" },
  { label: "PGDAV College, New Delhi", value: "PGDAV College, New Delhi" },
  { label: "Ponda Education Society Shri Ravi S. Naik College of Arts and Science, North Goa", value: "Ponda Education Society Shri Ravi S. Naik College of Arts and Science, North Goa" },
  { label: "Rathinam College of Arts and Science, Coimbatore", value: "Rathinam College of Arts and Science, Coimbatore" },
  { label: "S.T. Hindu College, Nagercoil", value: "S.T. Hindu College, Nagercoil" },
  { label: "Satyawati College, Delhi", value: "Satyawati College, Delhi" },
  { label: "Sree Kerala Varma College, Thrissur", value: "Sree Kerala Varma College, Thrissur" },
  { label: "Sree Narayana College, Kollam", value: "Sree Narayana College, Kollam" },
  { label: "Sree Neelakanda Govt. Sanskrit College, Pattambi", value: "Sree Neelakanda Govt. Sanskrit College, Pattambi" },
  { label: "Sri Nehru Maha Vidyalaya College of Arts and Science, Coimbatore", value: "Sri Nehru Maha Vidyalaya College of Arts and Science, Coimbatore" },
  { label: "Sri Ramakrishna College of Arts & Science for Women, Coimbatore", value: "Sri Ramakrishna College of Arts & Science for Women, Coimbatore" },
  { label: "St. Ann's College for Women, Hyderabad", value: "St. Ann's College for Women, Hyderabad" },
  { label: "St. Joseph's College for Women, Alappuzha", value: "St. Joseph's College for Women, Alappuzha" },
  { label: "St. Xavier's College for Women, Aluva", value: "St. Xavier's College for Women, Aluva" },
  { label: "Sullamussalam Science College, Areekode", value: "Sullamussalam Science College, Areekode" },
  { label: "Thanthai Periyar Government Arts and Science College (Autonomous), Tiruchirappalli", value: "Thanthai Periyar Government Arts and Science College (Autonomous), Tiruchirappalli" },
  { label: "The New College, Chennai", value: "The New College, Chennai" },
  { label: "Thiruvalluvar Government Arts College", value: "Thiruvalluvar Government Arts College" },
  { label: "Other Government College", value: "Other Government College" },
  { label: "Other Private College", value: "Other Private College" },
  ]